package io.java.pvz.net.protocol;

public enum MessageType {
    HELLO,
    HEARTBEAT,
    ERROR,

    LOGIN,
    LOGOUT,
    SIGNUP_REGISTER,
    SIGNUP_PICK_QUESTION,
    FORGOT_PASSWORD,
    CHECK_SECURITY_QUESTION,
    RESET_PASSWORD,
    FETCH_USER_STATE,
    PUSH_USER_STATE,

    UPDATE_USERNAME,
    UPDATE_EMAIL,
    UPDATE_NICKNAME,
    UPDATE_PASSWORD,

    CHECK_USER_ONLINE,
    CHALLENGE_INVITE,
    CHALLENGE_RESPONSE,
    QUEUE_JOIN_RANDOM,
    QUEUE_LEAVE,
    MATCH_FOUND,

    MATCH_STATE_SYNC,
    MATCH_ACTION,
    MATCH_ACTION_BROADCAST,
    MATCH_SURRENDER,
    MATCH_PAUSE_REQUEST,
    MATCH_RESUME_REQUEST,
    MATCH_PAUSE_STATE,
    MATCH_END,

    REACTION_SEND,

    LEADERBOARD_REQUEST,
    LEADERBOARD_RESPONSE,
    SCORE_SUBMIT
}
