package models.game;

public enum GameEvent {
    GAME_STARTED,
    GAME_OVER,
    ZOMBIE_KILLED,
    SUN_COLLECTED,
    PLANT_PLACED,
    PLANT_LOST,
    WAVE_STARTED,
    WAVE_COMPLETED,
    LEVEL_COMPLETED,
    LAWNMOWER_TRIGGERED;
}
